# Generated by Django 4.2.13 on 2024-06-19 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='websitePassword',
            new_name='encryptedPassword',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='websiteUsername',
            new_name='username',
        ),
        migrations.AddField(
            model_name='website',
            name='encryptedSalt',
            field=models.CharField(default=django.utils.timezone.now, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='isLeaked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='isUserCreated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='userNotes',
            field=models.TextField(default=django.utils.timezone.now, max_length=9999),
            preserve_default=False,
        ),
    ]
