# Generated by Django 4.2.13 on 2024-06-20 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_websitepassword_website_encryptedpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='userId',
        ),
        migrations.AddField(
            model_name='website',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
