# Generated by Django 4.2.13 on 2024-06-20 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_website_userid_website_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
