# Generated by Django 4.2.13 on 2024-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_website_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='passwordStrength',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='website',
            name='userNotes',
            field=models.TextField(blank=True, max_length=9999),
        ),
    ]
