# Generated by Django 4.0.10 on 2024-06-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_website_passwordstrength_alter_website_usernotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='creationDate',
            field=models.TextField(blank=True, max_length=9999),
        ),
    ]
